# Main.yml file for Docker role definition

- name: Install the packages needed for Docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - gnupg
    - ca-certificates
    - curl
    - python3-pip # installs pip for python3

# https://docs.docker.com/engine/install/ubuntu/
- name: "Download the GPG Key"
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: "Add repository to repository list"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present

- name: "Update packages and install docker-ce"
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin

- name: "Install Docker Module via pip"
  pip:
    name: docker

- name: "Install Docker-compose Module via pip"
  pip:
    name: docker-compose

- name: "Add user ubuntu to group Docker"
  user:
    name: ubuntu
    groups: docker
    append: true
