# Main.yml file for Docker role definition

- name: Install the packages needed for Docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - gnupg
    - ca-certificates
    - curl

# https://docs.docker.com/engine/install/ubuntu/
- name: "Downloads the GPG Key"
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: "Adds repository to repository list"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present

- name: "Updates packages and installs docker-ce"
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
